###
//Create parking lots
POST http://localhost:3001/lot
Content-Type: application/json

{
    "location": 1
}

###
//Get parking lots
GET http://localhost:3001/lots

###
//Get parking lots by id
GET http://localhost:3001/lot/d805f089-6cd4-46cf-a541-55fe7c7ebe6d

###
//Update parking lots
PATCH http://localhost:3001/lot/88f71d25-d750-40ef-b4b7-15937a2602ae
Content-Type: application/json

{
    "location": 2,
    "status": 1
}

###
//Delete parking lots
DELETE http://localhost:3001/lot/f31eadb9-43d6-49e7-8478-11fdc2f9a063
