@startuml system-design
actor "User" as user
node "Bike-rent-backend node.js API" {
    component "Controller" as controller
    component "Middleware" as middleware
    component "Service" as service
    component "Model" as model
}
database "MYSQL" as database

user <--> controller
controller <--> middleware
middleware --> service
controller <--> service
service <--> model
model <--> database

@enduml